// Real-voice recordings for the word lists (Wikimedia Commons files used by Wiktionary).
// Generated by tools/build-audio-map.mjs - do not edit by hand.
// Keys are lowercase words without accents; null means no English recording was found.
// Words missing from this map are looked up live in the browser (see audio.js).
const AUDIO_MAP = {};
